### ISSUE TITLE
RUtorrent bug

### ISSUE THREAD

**Issue by hexed** [Log1x/docker-rtorrent-flood#1]
The rtorrent.rc is not properly marking /tmp/.rtorrent.sock permissoins.

**Comment by Log1x** [comment]
Will check this out and finish tweaking any bugs ASAP. This container is somewhat a WIP still and was made for personal use.

**Comment by hexed** [comment]
I think I figured it out;

Add to nginx.conf 

user torrent root;

**Comment by Log1x** [comment]
Care to submit a PR?

**Comment by Log1x** [comment]
Fixed in #8
