### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by suffixdesign** [Log1x/docker-rtorrent-flood#11]
l'm getting a lot of 'permission denied' errors in my log. eg:
`df: /data/docker-storage/overlay2/5a261d166de98aa4d62351144d30472a66862ba50b9963fbd2f44a2daeeeaad3/merged/sys/fs/cgroup/memory: Permission denied`
other than that, the contatiner works fine.
wonder what could cause the issue?

**Comment by Log1x** [comment]
Hmm, never seen this before and I have had this running on multiple boxes for a few years now.

Is it being spammed repeatedly? Whats the host system look like? Are you using SELinux?

**Comment by suffixdesign** [comment]
l'm using a simple desktop PC with openmediavault 5.6.23 (debian buster based) with an installed docker (v5.20.10.12) and portainer (v2.11).
yes, it constantly spams the log.
l migrated the main docker storage away from /var/lib/docker to a more spacious volume, in about two months ago, but everything worked fine after that.
the problem arose after l updated the dockerd in omv.

edit: thanks for the quick reply!

**Comment by Log1x** [comment]
did you just start using this container or were you using it fine prior to updating dockerd? could it be a bug? this container is super simple compared to most – i dont see how it could be the cause of an issue like that. :(

im trying to Google around for `/merged/sys/fs/cgroup/memory: Permission denied` but not seeing much recent outside of a 2021 bug posted to Redhat that probably isn't related.

**Comment by suffixdesign** [comment]
no, l'm happily using your container for more than 2 years.
[_rtorrent-flood_logs.txt](https://github.com/Log1x/docker-rtorrent-flood/files/7919215/_rtorrent-flood_logs.txt)
here's a nice and crispy log.
yean, l know it's super simple, and that's why l'm using yours.

**Comment by suffixdesign** [comment]
hey Brandon!
l think l've found the root cause after an unexpected docker crash. as l'm using rtorrent-flood extensively for more than 2 years, my fiveminsnapshot.db file in history grew to 609MB, and that gave the _Cannot create a string longer than 0x1fffffe8 characters_ error in docker/portainer. after l deleted the file, everything is working now.
well, apart from the mysterious docker errors l mentioned above.
