### ISSUE TITLE
container "hangs" on start

### ISSUE THREAD

**Issue by Saboti** [Log1x/docker-rtorrent-flood#2]
Hi Log1x,

on startup of your Container I have the Problem that its "hanging" on the Command in the entrypoint.sh
`chown -R 1000:1000 /data /config /tmp /usr/local/flood`
If I comment it out everything is Working.

Regards Saboti

**Comment by fl0wfr** [comment]
Hi,
You have to wait several minutes, then the other processes start.
Regards

**Comment by realChesta** [comment]
Why does this happen? My container startup time is more than 10 minutes now, this can't be normal. Is there anything I can do to shorten the time?
