### ISSUE TITLE
container log full of entries

### ISSUE THREAD

**Issue by mmlody** [Log1x/docker-rtorrent-flood#4]
hello

i try to use docker image coker-rtorrent-flood
generally everything works ok byt my container log with this image have full of entries like below:

{"log":"Going to xmlrpc_createXmlrpcValue\n","stream":"stderr","time":"2020-02-19T11:28:04.534261843Z"}
{"log":"Back from createXmlrpcValue\n","stream":"stderr","time":"2020-02-19T11:28:04.534268285Z"}
{"log":"stringNew exiting\n","stream":"stderr","time":"2020-02-19T11:28:04.534275038Z"}
{"log":"stringNew entered\n","stream":"stderr","time":"2020-02-19T11:28:04.534281149Z"}
{"log":"Going to xmlrpc_createXmlrpcValue\n","stream":"stderr","time":"2020-02-19T11:28:04.534287492Z"}
{"log":"Back from createXmlrpcValue\n","stream":"stderr","time":"2020-02-19T11:28:04.534320253Z"}
{"log":"stringNew exiting\n","stream":"stderr","time":"2020-02-19T11:28:04.53432905Z"}
{"log":"stringNew entered\n","stream":"stderr","time":"2020-02-19T11:28:04.534335883Z"}
{"log":"Going to xmlrpc_createXmlrpcValue\n","stream":"stderr","time":"2020-02-19T11:28:04.534342074Z"}
{"log":"Back from createXmlrpcValue\n","stream":"stderr","time":"2020-02-19T11:28:04.534348216Z"}
{"log":"stringNew exiting\n","stream":"stderr","time":"2020-02-19T11:28:04.534365017Z"}
{"log":"stringNew entered\n","stream":"stderr","time":"2020-02-19T11:28:04.5343718Z"}
{"log":"Going to xmlrpc_createXmlrpcValue\n","stream":"stderr","time":"2020-02-19T11:28:04.534378793Z"}
{"log":"Back from createXmlrpcValue\n","stream":"stderr","time":"2020-02-19T11:28:04.534417587Z"}
{"log":"stringNew exiting\n","stream":"stderr","time":"2020-02-19T11:28:04.534424841Z"}
{"log":"stringNew entered\n","stream":"stderr","time":"2020-02-19T11:28:04.534433006Z"}
{"log":"Going to xmlrpc_createXmlrpcValue\n","stream":"stderr","time":"2020-02-19T11:28:04.534440029Z"}
{"log":"Back from createXmlrpcValue\n","stream":"stderr","time":"2020-02-19T11:28:04.534447092Z"}
{"log":"stringNew exiting\n","stream":"stderr","time":"2020-02-19T11:28:04.534453815Z"}
{"log":"stringNew entered\n","stream":"stderr","time":"2020-02-19T11:28:04.534459085Z"}
{"log":"Going to xmlrpc_createXmlrpcValue\n","stream":"stderr","time":"2020-02-19T11:28:04.534494832Z"}
{"log":"Back from createXmlrpcValue\n","stream":"stderr","time":"2020-02-19T11:28:04.53450423Z"}
{"log":"stringNew exiting\n","stream":"stderr","time":"2020-02-19T11:28:04.534510551Z"}
{"log":"stringNew entered\n","stream":"stderr","time":"2020-02-19T11:28:04.534516312Z"}
{"log":"Going to xmlrpc_createXmlrpcValue\n","stream":"stderr","time":"2020-02-19T11:28:04.534521944Z"}
{"log":"Back from createXmlrpcValue\n","stream":"stderr","time":"2020-02-19T11:28:04.534529598Z"}
{"log":"stringNew exiting\n","stream":"stderr","time":"2020-02-19T11:28:04.53453624Z"}
{"log":"stringNew entered\n","stream":"stderr","time":"2020-02-19T11:28:04.534542853Z"}
{"log":"Going to xmlrpc_createXmlrpcValue\n","stream":"stderr","time":"2020-02-19T11:28:04.534549035Z"}
{"log":"Back from createXmlrpcValue\n","stream":"stderr","time":"2020-02-19T11:28:04.534596083Z"}
{"log":"stringNew exiting\n","stream":"stderr","time":"2020-02-19T11:28:04.534609137Z"}
{"log":"stringNew entered\n","stream":"stderr","time":"2020-02-19T11:28:04.534615339Z"}
{"log":"Going to xmlrpc_createXmlrpcValue\n","stream":"stderr","time":"2020-02-19T11:28:04.534747849Z"}
{"log":"Back from createXmlrpcValue\n","stream":"stderr","time":"2020-02-19T11:28:04.534762226Z"}
{"log":"stringNew exiting\n","stream":"stderr","time":"2020-02-19T11:28:04.534769731Z"}
{"log":"stringNew entered\n","stream":"stderr","time":"2020-02-19T11:28:04.534776052Z"}
{"log":"Going to xmlrpc_createXmlrpcValue\n","stream":"stderr","time":"2020-02-19T11:28:04.534811779Z"}
{"log":"Back from createXmlrpcValue\n","stream":"stderr","time":"2020-02-19T11:28:04.534820907Z"}
{"log":"stringNew exiting\n","stream":"stderr","time":"2020-02-19T11:28:04.534827148Z"}
{"log":"stringNew entered\n","stream":"stderr","time":"2020-02-19T11:28:04.53483351Z"}
{"log":"Going to xmlrpc_createXmlrpcValue\n","stream":"stderr","time":"2020-02-19T11:28:04.534840684Z"}
{"log":"Back from createXmlrpcValue\n","stream":"stderr","time":"2020-02-19T11:28:04.534846344Z"}
{"log":"stringNew exiting\n","stream":"stderr","time":"2020-02-19T11:28:04.534852085Z"}
{"log":"stringNew entered\n","stream":"stderr","time":"2020-02-19T11:28:04.534857856Z"}
{"log":"Going to xmlrpc_createXmlrpcValue\n","stream":"stderr","time":"2020-02-19T11:28:04.534864208Z"}
{"log":"Back from createXmlrpcValue\n","stream":"stderr","time":"2020-02-19T11:28:04.534898162Z"}
{"log":"stringNew exiting\n","stream":"stderr","time":"2020-02-19T11:28:04.534910035Z"}
{"log":"stringNew entered\n","stream":"stderr","time":"2020-02-19T11:28:04.534916827Z"}
{"log":"Going to xmlrpc_createXmlrpcValue\n","stream":"stderr","time":"2020-02-19T11:28:04.53492328Z"}
{"log":"Back from createXmlrpcValue\n","stream":"stderr","time":"2020-02-19T11:28:04.534930192Z"}
{"log":"stringNew exiting\n","stream":"stderr","time":"2020-02-19T11:28:04.534936464Z"}
{"log":"stringNew entered\n","stream":"stderr","time":"2020-02-19T11:28:04.534943217Z"}
{"log":"Going to xmlrpc_createXmlrpcValue\n","stream":"stderr","time":"2020-02-19T11:28:04.534950771Z"}
{"log":"Back from createXmlrpcValue\n","stream":"stderr","time":"2020-02-19T11:28:04.535008189Z"}
{"log":"stringNew exiting\n","stream":"stderr","time":"2020-02-19T11:28:04.535016846Z"}
{"log":"stringNew entered\n","stream":"stderr","time":"2020-02-19T11:28:04.535022095Z"}
{"log":"Going to xmlrpc_createXmlrpcValue\n","stream":"stderr","time":"2020-02-19T11:28:04.535027035Z"}
{"log":"Back from createXmlrpcValue\n","stream":"stderr","time":"2020-02-19T11:28:04.535031994Z"}
{"log":"stringNew exiting\n","stream":"stderr","time":"2020-02-19T11:28:04.535037124Z"}

This is ~5MB entries per second. Why ? How to correct this state ?

**Comment by Log1x** [comment]
it seems to be an issue with the Xmlrpc compiled with Alpine's rTorrent package. I may need to re-write it to compile from source.
