### ISSUE TITLE
Information to connect Sonarr/Radarr

### ISSUE THREAD

**Issue by artik** [Log1x/docker-rtorrent-flood#6]
Hi! image built and working. I have access to flood, and all seems to work. Looking for the Sonarr configuration regarding your `nginx.conf`, but I can't figure what to set in Sonarr downloadClients.

I tried:

```
Host: 192.168.0.2
Port: 3001
Url Path: /
Use SSL: (unckecked)
Username: admin
Password: socket
```

Nginx returns me:

```
*1 connect() to unix:/tmp/.rtorrent.sock failed (13: Permission denied) while connecting to upstream, client: 172.17.0.1, server: , request: "POST // HTTP/1.1", upstream: "scgi://unix:/tmp/.rtorrent.sock:", host: "192.168.0.2:3001"
```

Tried also many other possibilities, but can't connect. Do I have to edit something in `rtorrent.rc` ?
Help is welcome

**Comment by Log1x** [comment]
Fixed in #8
